{% set version = "5.0.0" %}

package:
  name: azure-mgmt
  version: {{ version }}

source:
  fn: azure-mgmt-{{ version }}.zip
  url: https://pypi.io/packages/source/a/azure-mgmt/azure-mgmt-{{ version }}.zip
  md5: 8a31a340614fd4ce205c9dbe7ccd082b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
    - azure-mgmt-compute ==0.20.1
    - azure-mgmt-network ==0.20.1
    - azure-mgmt-resource ==0.20.1
    - azure-mgmt-storage ==0.20.0
  run:
    - python
    - azure-mgmt-compute ==0.20.1
    - azure-mgmt-network ==0.20.1
    - azure-mgmt-resource ==0.20.1
    - azure-mgmt-storage ==0.20.0

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.compute
    - azure.mgmt.network
    - azure.mgmt.storage
    - azure.mgmt.resource
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: Microsoft Azure Client Libraries for Python

extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
